services:
  - type: web
    name: movie-app
    env: static
    buildCommand: pnpm install && pnpm build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: your_api_url 